CREATE TABLE user (
	id INTEGER PRIMARY KEY,
	username VARCHAR(64) NOT NULL,
	password VARCHAR(64) NOT NULL
)

CREATE TABLE job (
	id INTEGER PRIMARY KEY,
	user_id INTEGER REFERENCES user(id),
	token VARCHAR(32) NOT NULL,
	status VARCHAR(16) NOT NULL
)
